### ISSUE TITLE
You may want to advocate using the pynetworktables2js built-in server

### ISSUE THREAD

**Issue by virtuald** [FRCDashboard/FRCDashboard#11]
Instead of distributing a server.py and forcing users to carry it around, you can do this instead:

```sh
python -m pynetworktables2js
```

It provides essentially the same capabilities as the sample server, and that's one less piece of boilerplate that users have to carry around.

**Comment by ErikBoesen** [comment]
Completely forgot about this. Fixing.

**Comment by ErikBoesen** [comment]
Just one quick question: what would the Windows equivalent of this command be? I'm guessing

    start py -3 -m pynetworktables2js

but I'm not sure.

**Comment by virtuald** [comment]
That's exactly it.

**Comment by ErikBoesen** [comment]
Okay. Pushing in just a moment
