### ISSUE TITLE
As a non-technical user, I want an installer

### ISSUE THREAD

**Issue by virtuald** [FRCDashboard/FRCDashboard#12]
Especially if I actually create a [single executable version of pynetworktables2js](https://github.com/robotpy/pynetworktables2js/issues/15), this could be really helpful.
- Installs the single executable somewhere
- Provides launch files on the desktop

Just a thought.

**Comment by ErikBoesen** [comment]
This is a good idea. Definitely on the roadmap.

**Comment by virtuald** [comment]
Made that single-exe version of pynetworktables2js.
