### ISSUE TITLE
Windows - server doesn't launch on npm start

### ISSUE THREAD

**Issue by czhao39** [FRCDashboard/FRCDashboard#14]
When I run `npm start` with the default code, a blank Electron window opens but no content appears. However, it does work in the browser with `python pynetworktables2js`. Also, all the content shows up properly in Electron in Linux (Fedora), so it seems like this issue is specific to Windows.

**Comment by ErikBoesen** [comment]
Try pressing `Ctrl+R` to refresh. I've seen this bug around a couple times, and I'm guessing that's the problem.

**Comment by czhao39** [comment]
That does not seem to do anything.

**Comment by ErikBoesen** [comment]
Have you installed `pynetworktables2js`?

**Comment by ErikBoesen** [comment]
If you have and the issue still persists, you can try running `start py -3 -m pynetworktables2js`.

**Comment by czhao39** [comment]
Starting `pynetworktables2js` before running `npm start` worked. Thanks!

**Comment by ErikBoesen** [comment]
I'm going to keep this open since this is an annoying workaround at best. Good luck this season regardless!

**Comment by czhao39** [comment]
I'm sorry, I figured out the problem. I'm using a virtualenv, and I do not have the `py` command in the virtualenv. Therefore, `pynetworktables2js` was running in my host machine's python environment, which does not have all the necessary packages installed.

**Comment by ErikBoesen** [comment]
Ah, got it. Good to hear. Good luck this season!
