### ISSUE TITLE
The installer script for mjpg-streamer leads to a 404

### ISSUE THREAD

**Issue by StoneMoney** [FRCDashboard/FRCDashboard#18]
This link in the readme: https://raw.githubusercontent.com/robotpy/robotpy-wpilib/master/installer/installer.py

**Comment by auscompgeek** [comment]
It lives in its own PyPI package now. `pip install robotpy-installer`, then run `robotpy-installer`.

**Comment by auscompgeek** [comment]
Either way, you don't actually need mjpg-streamer any more, WPILib's CameraServer class lets you have an MJPEG stream without using mjpg-streamer.

**Comment by ErikBoesen** [comment]
Someone care to make a pull request clarifying this? I meant to get back to this and totally forgot.

**Comment by ErikBoesen** [comment]
@ianzullo Look at this. In the README we shouldn't say that people should download `installer.py` as they can now use the package `robotpy-installer` or use WPILib's CameraServer class.
