### ISSUE TITLE
When I try to run pynetworktables2js, I get this error.

### ISSUE THREAD

**Issue by Jetlogan** [FRCDashboard/FRCDashboard#19]
`Traceback (most recent call last):
  File "pyinstaller\shim.py", line 6, in <module>
  File "pynetworktables2js\__main__.py", line 81, in main
  File "pynetworktables2js\__main__.py", line 37, in init_networktables
AttributeError: Values instance has no attribute 'dashboard'
Failed to execute script shim`

Anyone know what this means?

**Comment by czhao39** [comment]
Have you upgraded to the newest version of `pynetworktables2js`? That should fix the error.

**Comment by Jetlogan** [comment]
I mean in the error it says pynetworktables2js so I guess.

**Comment by czhao39** [comment]
But do you have the newest version? Run `pip install -U pynetworktables2js` to upgrade. This was an error in the previous release and should be fixed now.

**Comment by Jetlogan** [comment]
I'm using the Windows version.

**Comment by ErikBoesen** [comment]
In that case, `py -3 -m pip install -U pynetworktables2js`.

**Comment by Jetlogan** [comment]
In CMD right?

**Comment by ErikBoesen** [comment]
Yes.

**Comment by ErikBoesen** [comment]
Did you figure this out?
