### ISSUE TITLE
No icon for compiled executables

### ISSUE THREAD

**Issue by ErikBoesen** [FRCDashboard/FRCDashboard#33]

**Comment by ErikBoesen** [comment]
@ianzullo Take a swing at this. FRCDashboard is the boilerplate system I wrote for making driving dashboards.

**Comment by ianzullo** [comment]
Does an icon already exist or does one need to be created?

**Comment by ErikBoesen** [comment]
@ianzullo I've used [the organization profile photo](https://avatars2.githubusercontent.com/u/19158558) before, but you're welcome to make a better one if you wish.
