### ISSUE TITLE
Network Tables

### ISSUE THREAD

**Issue by Bananajojo123** [FRCDashboard/FRCDashboard#37]
How do we grab network table values and post network table values?

**Comment by ErikBoesen** [comment]
For fetching values from NetworkTables, you can use `NetworkTables.getValue('/path/to/value')`. For putting them, you can use `NetworkTables.putValue('/path/to/value', value)`.

You can also use
```js
NetworkTables.addKeyListener('/SmartDashboard/example_variable', (key, value) => {
    // Do things with value
}
```
to create a listener for the value being changed.

**Comment by Bananajojo123** [comment]
What is the name of the network table? Can you set the name of the network table?

**Comment by ErikBoesen** [comment]
You will need to give the full path to the variable. So, 'SmartDashboard/valuename` if you're using the `SmartDashboard` table, or `robot/valuename`, etc.

**Comment by Bananajojo123** [comment]
What libraries do I have to import?

**Comment by ErikBoesen** [comment]
None.

**Comment by Bananajojo123** [comment]
In the console, IPC is not defined in the NetworkTables.js file. In the ui.js file, require is not defined.

**Comment by ErikBoesen** [comment]
Yup, I just noticed some issues with our implementation. In theory you should not have to do any imports yourself. We will be fixing this issue pretty soon. See #40 for some more information.

**Comment by ErikBoesen** [comment]
@rakusan2 Do you have any idea what could be going wrong? This seems like a pretty integral issue.

**Comment by rakusan2** [comment]
Sorry, back when you removed tryIPC.js and declared the ipc variable somewhere else, I forgot to inform you that based on index.html, networktables.js runs before ui.js.
Therefor the ipc declaration has to be at the beginning of networktables.js

**Comment by Bananajojo123** [comment]
Thanks for that! But what about require is not defined in all of the .js files

**Comment by ErikBoesen** [comment]
Working on fixing this, I'm also fixing #38 in the process. Will let you know when I've finished.

**Comment by rakusan2** [comment]
After moving the ipc declaration to networktables.js everything seems to be working fine for me including require. 
So I have no idea what is causing require to not be defined for you

**Comment by Bananajojo123** [comment]
It's only relevant when you use the network tables editor in the dashboard. It's one of the components.

**Comment by ErikBoesen** [comment]
Alright, this should be fixed; feel free to pull changes.

**Comment by ErikBoesen** [comment]
@Bananajojo123 I recommend using OutlineViewer, as the Tuning interface has been [deprecated](#39). (Note that you will still be able to use it through its [addon](https://github.com/FRCDashboard/addon-Tuning) if you wish.)

**Comment by Bananajojo123** [comment]
Because you added connection.js, it has require is not defined. The networktables.js also has the same error. And in ui.js, Cannot read property 'addKeyListener' of undefined at ui.js:44.

**Comment by ErikBoesen** [comment]
That's really odd. This worked fine for me, but shouldn't have. I'll fix this momentarily.

**Comment by Bananajojo123** [comment]
Would you like my code?

**Comment by Bananajojo123** [comment]
No, only the error that was being caused from connection.js and not networktables.js.

**Comment by ErikBoesen** [comment]
If you want to share your repository with me, feel free.

**Comment by rakusan2** [comment]
Are you running this through electron? and what version?

**Comment by Bananajojo123** [comment]
Here: https://github.com/MRT3216/MRT3216-2018-PowerUp/tree/master/ROBOTICS/FRCDashboard-master/FRCDashboard-master

**Comment by rakusan2** [comment]
After moving the ipc declaration to networktables.js I ran your code and got this 
![image](https://user-images.githubusercontent.com/10575235/35188062-ffdd5160-fdfc-11e7-9a01-dc051b0e1490.png)

**Comment by rakusan2** [comment]
I would recommend updating it with the latest changes to this project

**Comment by Bananajojo123** [comment]
done

**Comment by Bananajojo123** [comment]
try again

**Comment by rakusan2** [comment]
The script connections.js should run after networktables.js but you have that script in the head

**Comment by rakusan2** [comment]
You are also missing an element with `id="arm-position"`

**Comment by Bananajojo123** [comment]
done

**Comment by Bananajojo123** [comment]
It's still giving me the error

**Comment by ErikBoesen** [comment]
Putting `<script>` tags in the `<head>` will cause them to be run before the page loads. Typically it's a good idea to put them (in order of dependency) immediately before the closing `</body>` tag.

**Comment by Bananajojo123** [comment]
I did move them right before the </body>

**Comment by Bananajojo123** [comment]
I put them in order, near the </body>

**Comment by ErikBoesen** [comment]
By the way, I'd recommend that you think about moving your robot code, dashboard code, etc. into separate repositories. This allows them to be managed much more easily.

**Comment by rakusan2** [comment]
After the change that you made, the only error that I see now is in ui.js and it is caused by no element having an id of "arm-position"

**Comment by ErikBoesen** [comment]
Also, typically it's not a good idea to download a zip of a repository, at least when you're planning to put it into a repository. Don't ever commit zip files. The Tuning addon shouldn't have its full directory present, either.

**Comment by ErikBoesen** [comment]
(This isn't so much related to this issue, just some general tips on your code.)

**Comment by rakusan2** [comment]
If I may add my own tip.
Add bin folders to your .gitignore file since those folders are usually large and need to be recreated on every system anyway

**Comment by Bananajojo123** [comment]
So I made some changes and the new repository is here: https://github.com/MRT3216/Dashboard.
I still can't figure out what's going on. 
![image](https://user-images.githubusercontent.com/20143106/35188570-d94755a8-fdf4-11e7-849f-4d129b9048f9.png)

**Comment by rakusan2** [comment]
This need to run through electron not through a browser as that functionality had been removed

**Comment by Bananajojo123** [comment]
Thanks! :)

**Comment by ErikBoesen** [comment]
Oh, yeah, that's the problem. Glad we could help! Let us know if you need anything.

**Comment by ErikBoesen** [comment]
I see you've moved to a new repository, good choice.

Some other recommendations for your code:
* Commit titles should be written in the imperative tense. So, 'Add...' rather than 'Added...'. They should additionally be descriptive (avoid "more updates", etc.) and use proper capitalization.
* Storing binary-format documents in git is typically a bad idea unless you actually have to. Rather than a Word document, might I suggest you use a Markdown file? Markdown can easily be viewed both natively on GitHub or as plain text, and doesn't require that users have a closed-source product installed, nor that they spend time opening such a product. You could recreate your current document by creating `control_system.md` with the following content:
```md
* High/low gear drive train
* Lifter (button)
* Intake (in and out)
* Climber (winch) (up and down)
* Tank drive
    * Click one joystick and push other joystick to drive straight
```
* Your git config seems to be broken; you can enter the following commands to help GitHub properly associate your commits with your user account:

**Comment by Bananajojo123** [comment]
Ok, thanks! 👍

**Comment by Bananajojo123** [comment]
Also I saw that you made even more changes to the code. I was wondering if I should add that into my code.

**Comment by ErikBoesen** [comment]
Feel free. None of it is major, but you might benefit.

Just so you know, one of the reasons to keep your code in a separate repository is that you can use git to pull changes to the code and git will help you automatically integrate updates (and resolve conflicts if necessary).

**Comment by Bananajojo123** [comment]
Thanks!  😄

**Comment by Bananajojo123** [comment]
Also, Is there any way that you can launch developer options in the application?

**Comment by ErikBoesen** [comment]
@Bananajojo123 Comment out this line in `src/main.js`:
```js
mainWindow.setMenu(null);
```
You'll then be able to access the menus to open the developer options.

**Comment by rakusan2** [comment]
The second argument to `addKeyListener()` has to be a function.
This argument is currently not being checked but I will soon make a pull request where it will be
