### ISSUE TITLE
Electron app won't connect to localhost

### ISSUE THREAD

**Issue by Chandi-95** [FRCDashboard/FRCDashboard#40]
We've set up everything correctly on our Driver Station, but the application is stuck on connecting to the localhost. We haven't touched anything in the code either, except for changing the timer. Is there a way to bypass the connection to localhost/fix the connection issue?

![screenshot_1](https://user-images.githubusercontent.com/29168502/35186663-c7ecfcb8-fde5-11e7-8ab7-82be6f270e30.png)

**Comment by ErikBoesen** [comment]
Are you hosting a simulator on your computer? Otherwise, there won't be anything on `localhost` to connect to.

**Comment by ErikBoesen** [comment]
Hold on, you're right, there seems to be an issue with some recent changes. Give me a moment, I'll see what I can do.

**Comment by ErikBoesen** [comment]
This should be fixed now. Feel free to pull changes.
