### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by ErikBoesen** [FRCDashboard/FRCDashboard#44]
The current one is quite low-res, and not very professional. We should make a new one.

**Comment by anilkilic** [comment]
Hey,

I turned your current logo into vector (.svg) also provided some higher resolution pngs. If you want to use until you make a new one.

![frc_740x632](https://user-images.githubusercontent.com/2311397/35191790-5ba5e05a-fe95-11e7-98e9-d7c893eef179.png)
[Archive.zip](https://github.com/FRCDashboard/FRCDashboard/files/1649587/Archive.zip)

**Comment by ErikBoesen** [comment]
Woah, thanks, that's awesome! @ianzullo Can you implement these images?

**Comment by ErikBoesen** [comment]
You know, the current one is pretty okay given that we have a vector version now.
