### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by bjhunt7520** [FRCDashboard/FRCDashboard#48]
![capture](https://user-images.githubusercontent.com/22771522/35244648-1776cd92-ff7e-11e7-9194-783c1e646739.PNG)

**Comment by ErikBoesen** [comment]
This should be fixed by #47, please pull changes. Let me know if you still have this issue.

**Comment by rakusan2** [comment]
Sorry but that change was only for the window not for main

**Comment by rakusan2** [comment]
This error happened in the connection callback. 
My guess is that webContents is being used an a window that has not yet been initialized.

**Comment by ErikBoesen** [comment]
Whoops, pardon me, I didn't look to see that this wasn't the same error that you previously posted.

**Comment by ErikBoesen** [comment]
#49

**Comment by Bananajojo123** [comment]
It didn't fix it :(

**Comment by Bananajojo123** [comment]
It didn't fix it :(     #47
