### ISSUE TITLE
& missing in main.js line 53

### ISSUE THREAD

**Issue by Bananajojo123** [FRCDashboard/FRCDashboard#51]
You have to add a & in line 53 of main.js. The line looks like this client.Assign(mesg.val, mesg.key,(mesg.flags & 1) === 1);. Add another & near the current one.

**Comment by ErikBoesen** [comment]
This is a bitwise AND operation. It's supposed to be this way. [More information](https://en.wikipedia.org/wiki/Bitwise_operations_in_C)

**Comment by Bananajojo123** [comment]
It works with &&

**Comment by ErikBoesen** [comment]
No, it doesn't. `&&` and `&` are fundamentally different operations. While it may work the same in some cases, you're doing a different operation and the outputs will be different. `x & 1` is `true` if the last bit of `x` is `1`. `x && 1` is `true` if `x` is anything other than 0. We use the bitwise AND here intentionally, it does not need to and should not be changed.
