### ISSUE TITLE
Errors in main.js

### ISSUE THREAD

**Issue by Bananajojo123** [FRCDashboard/FRCDashboard#53]
![capture](https://user-images.githubusercontent.com/20143106/35761593-949f7978-0847-11e8-9ad1-bb65eada5429.PNG)

#47  Didn't help

Repository: https://github.com/MRT3216/Dashboard

**Comment by ErikBoesen** [comment]
@rakusan2

**Comment by ErikBoesen** [comment]
Will be fixed when #56 gets corrected.

**Comment by ErikBoesen** [comment]
This should have been fixed by #57.
