### ISSUE TITLE
Error when starting application 

### ISSUE THREAD

**Issue by Chandi-95** [FRCDashboard/FRCDashboard#55]
![screenshot_2](https://user-images.githubusercontent.com/29168502/35769711-16c534ac-08dd-11e8-9808-174df55411fe.png)

Whenever we start the application, this error comes up. Is there a way to fix this?

**Comment by ErikBoesen** [comment]
@rakusan2 Any ideas about this?

**Comment by Chandi-95** [comment]
![screenshot_1](https://user-images.githubusercontent.com/29168502/35770359-7eae3618-08e7-11e8-80c4-dabfe936bd14.png)

Fixed it. 
 Changed "Window" to "mainWindow" at line 119.

**Comment by ErikBoesen** [comment]
This is a big issue. Do you mind contributing this change?

**Comment by Chandi-95** [comment]
Done.

**Comment by rakusan2** [comment]
Sorry about that.
I had made the change late at night and I must have missed that
