### ISSUE TITLE
Writing Values

### ISSUE THREAD

**Issue by HackerVis** [FRCDashboard/FRCDashboard#58]
I know this isn't an error with your code, but I was wondering , since no where else online, if there was any way to write values to Network tables to set things such ad the "gear" or "speed" of the robot. If so will you please let me know?

**Comment by ErikBoesen** [comment]
`NetworkTables.putValue('/path/to/value')`

There are a couple examples of this in the code.

If the value isn't in NetworkTables, there's not much you can do other than connect a NT value to your robot's speed in your robot code. Note that this may be slow.

**Comment by HackerVis** [comment]
Thank you!
