### ISSUE TITLE
Question NOT error on developer.

### ISSUE THREAD

**Issue by HackerVis** [FRCDashboard/FRCDashboard#59]
I remember there was a way to turn or "toggle" developer tools, but in this code I cannot find how to do that. Or, in other words, I cannot find the question you previously answered to fix or help this.

**Comment by ErikBoesen** [comment]
Assuming you fixed this. If you didn't, you can comment out the `mainWindow.setMenu(null);` line in `main.js`.

**Comment by ErikBoesen** [comment]
Actually, given that this has confused a great many people, I'm going to remove that line outright.
