### ISSUE TITLE
NetworkTables cannot access values

### ISSUE THREAD

**Issue by eAUE** [FRCDashboard/FRCDashboard#60]
All the values in the `NetworkTables` object are null. `NetworkTables.isRobotConnected()` returns `true` but if we try to get any values from the robot, they return undefined. `pynetworktables2js` is installed, and all dependencies are up to date. Running `NetworkTables.getKeys()` returns an empty array. I can confirm using the FRC outline viewer that the keys exist and are accessible. 

[NetworkTablesNotWorkingTrim.zip](https://github.com/FRCDashboard/FRCDashboard/files/1713588/NetworkTablesNotWorkingTrim.zip)

**Comment by ErikBoesen** [comment]
@rakusan2

**Comment by rakusan2** [comment]
Sorry, 
This has happened due to a bad optimisation

**Comment by eAUE** [comment]
This still doesn't work.

**Comment by rakusan2** [comment]
Have you updated the wpilib-nt-client to?

**Comment by eAUE** [comment]
It's at 5.6.0 and I pulled the changes made to the repository.

![image](https://user-images.githubusercontent.com/22606608/36127626-6acf3b32-102c-11e8-927e-1a00d75f0920.png)

**Comment by rakusan2** [comment]
The highest version that I have published is 1.6.0

**Comment by ErikBoesen** [comment]
@eAUE That command is getting the version of `npm`, not `wpilib-nt-client`.

**Comment by rakusan2** [comment]
Try the command `npm ls - - depth=0`

**Comment by eAUE** [comment]
Oh yeah, sorry. Here's the real screenshot:
![image](https://user-images.githubusercontent.com/22606608/36128101-97ca1bd2-102e-11e8-9466-0b97b4ec7561.png)

**Comment by rakusan2** [comment]
In main.js does the `client.addListener` have a second parameter with a value of `true`?

**Comment by eAUE** [comment]
Yes, it does: 
![image](https://user-images.githubusercontent.com/22606608/36129082-6a07274e-1033-11e8-92c2-f0ae1370368d.png)

**Comment by rakusan2** [comment]
Can you add this line to main.js `client.startDebug('NT-Client', 1)` and send me the output from the console?

**Comment by eAUE** [comment]
Yeah, I'll be able to test that on Wednesday at the earliest.
