### ISSUE TITLE
Feature request: Automatically try to reconnect after unexpected disconnect

### ISSUE THREAD

**Issue by Chris2fourlaw** [FRCDashboard/FRCDashboard#65]
Helpful when robot code restarts.

**Comment by rakusan2** [comment]
I will need to update the client to ensure that all of the keys sync once it connects instead of the server just sending what it has.
I should be done with that tonight.

**Comment by rakusan2** [comment]
Sorry that it took longer than I thought but due to my busy week I have been making lots of bugs that needed to be fixed.

**Comment by Chris2fourlaw** [comment]
2f58b5d created a problem described in #70. Please reopen!

**Comment by ErikBoesen** [comment]
This is a separate issue.

**Comment by Chris2fourlaw** [comment]
No, the `client.setReconnectDelay(1000);` causes this

**Comment by ErikBoesen** [comment]
What I mean is that we have implemented the feature requested by this issue, and #70 is open to address the bug in the implementation.

**Comment by ErikBoesen** [comment]
@rakusan2 Can you fix this? And do you mind testing more stringently in the future?

**Comment by rakusan2** [comment]
I have fixed this in wpilib-nt-client@1.7.1
And I will be getting into the habit of trying everything in the simulator before creating a pull request

**Comment by ErikBoesen** [comment]
Awesome, thanks Thomas! @rakusan2
