### ISSUE TITLE
Window failed to load

### ISSUE THREAD

**Issue by Bananajojo123** [FRCDashboard/FRCDashboard#69]
When connecting to the FRC Driver station, the gyro moves and then in the console, it gives the error:

Window failed load. 
![error](https://user-images.githubusercontent.com/20143106/36347872-0247035e-1420-11e8-82fe-9f98d27d33bc.JPG)

It only occurs when the gameData key is being passed.

**Comment by Chris2fourlaw** [comment]
Is this a problem with your teams code?

**Comment by Chris2fourlaw** [comment]
Is there an error message when you close the window? Whats the console output in dev tools?

**Comment by Bananajojo123** [comment]
Never mind, we figured it out.
