### ISSUE TITLE
Not connecting to robot

### ISSUE THREAD

**Issue by frankfabregat** [FRCDashboard/FRCDashboard#74]
After downloading the project, without changing anything and installing npm, I run it with `npm start` and it starts successfully. However, when I put my team number in the connect prompt, it says in the console `trying to connect to roborio-5986.local` and `Sending status`, and it does not connect. I am connected to the robots network, and it appears connected in the drive station

**Comment by ErikBoesen** [comment]
Is it literally saying `(number)`?

**Comment by ErikBoesen** [comment]
Check your console to see if there are any errors logged.

**Comment by frankfabregat** [comment]
No, it has the team number 5986. There are no errors logged

**Comment by ErikBoesen** [comment]
@rakusan2

**Comment by andrewda** [comment]
Is your roboRIO's address really `roborio-5986.local`? AFAIK that format hasn't been the default hostname since 2015. Try `roborio-5986-frc.local` or your roboRIO's static IP address (if you've set one).

**Comment by ErikBoesen** [comment]
Oh, yup, that'll be the issue. I didn't notice there was no `-frc` there.

**Comment by andrewda** [comment]
https://github.com/FRCDashboard/FRCDashboard/blob/b7fa1c8aa2d9d49f1b5a03dbdfb1c96f49c01177/src/connection.js#L51

Bit misleading in the code there, should probably be `roborio-XXXX-frc.local`.

**Comment by ErikBoesen** [comment]
Fixed.

**Comment by frankfabregat** [comment]
Ok, thank you. I will try it as soon as possible

**Comment by rakusan2** [comment]
Sorry, I have not been keeping up with the latest name changes

**Comment by ErikBoesen** [comment]
@rakusan2 No problem man.

**Comment by frankfabregat** [comment]
It still says `sending status` and not doing anything after updating it

**Comment by andrewda** [comment]
🤔 Can you `ping roborio-5986-frc.local` from the computer you're running the dashboard from and check to see if you get a response?
