### ISSUE TITLE
Compatibility Issues with 2019 FRC Alpha Release Code

### ISSUE THREAD

**Issue by pratBruns** [FRCDashboard/FRCDashboard#77]
My team (#4028 - the Beak Squad) is new to using the dashboard, and up to this point, it has worked great. We used it at the CORI event and it performed without error. Now that I am starting to try and use it with the 2019 FRC Alpha Code Base release, the dashboard has issues.

When I refresh the Dashboard (click View->Reload), the robot code running on the robot crashes with this error being displayed in the RioLog:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
# SIGSEGV (0xb) at pc=0xababd518, pid=3568, tid=0xa9e6d470
#
# JRE version: OpenJDK Runtime Environment (8.0_131-b57) (build 1.8.0_131-b57)
# Java VM: OpenJDK Client VM (25.131-b57 mixed mode, Evaluation linux-aarch32 )
# Problematic frame:
# C [libcscore.so+0x6f518] cs::MjpegServerImpl::ConnThread::SendStream(wpi::raw_socket_ostream&)+0x424
#
# Core dump written. Default location: //core or core.3568 (max size 2048 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid3568.log
#
# If you would like to submit a bug report, please visit:
# http://www.azulsystems.com/support/
#
```
I concluded that this is a problem with how the dashboard communicates with the Network Tables being broadcast by the robot. The only two means of connection between the computer that the dashboard code s running on and the robot would be 1) The wifi connection or 2) The network tables. It doesn't seem like the dashboard is outputting something to the robot that is making it crash, so it should be the network tables. At the point when the crash occurs, the dashboard is not trying to connect to any network table (when the dashboard loads I have it set up to wait for one of two buttons to be selected for either wireless or USB tether to connect to any port), so is there some background process being run by the dashboard that would interfere with the new code from FRC? When I run the 2018 Dashboard software from FRC, the robot code works fine, so it is definitely a problem with the Dashboard's compatibility with the new FRC code base. Thank you for inspecting this issue!

**Comment by ErikBoesen** [comment]
That error is coming from cscore, not anything necessarily tied to FRCDashboard. I'd guess it's occurring because of errors when loading the camera feed. If this doesn't occur when you try to load/reload the camera feed through a browser or other raw connection then we might have an issue, but otherwise this seems to not be a problem with this project.
