### ISSUE TITLE
Commands in FRCDashboard

### ISSUE THREAD

**Issue by roshanr10** [FRCDashboard/FRCDashboard#79]
I’m looking to develop a touch screen UI in FRCDashboard where clicking a given button would start a WPI Command, is there a built in mechanism to do so?

I looked around but didn’t find anything saying either way, I would appreciate if you could point me in the right direction.

**Comment by ErikBoesen** [comment]
Pretty much all communication with your robot through FRC Dashboard runs through NetworkTables. In your code you can check the value of a NetworkTables variable, modified by your dashboard, and use that to start the command. That's the best method I can think of off the top of my head; I personally have never used command-based architecture so there may be a better way. Does this make sense?
