### ISSUE TITLE
Enhanced Logging Unavailable

### ISSUE THREAD

**Issue by FRC-3277** [FRCDashboard/FRCDashboard#80]
We had a little trouble working with the project initially getting the project started.  We realized we didn't have code yet on the RoboRIO which was the cause of the issue, but there wasn't any logging to fall back on to show what we were doing wrong.

Love this thing btw!

**Comment by ErikBoesen** [comment]
If there's no RIO code to exchange data over NetworkTables with, there's nothing I can do. Since you need to run the driverstation at the same time as FRC Dashboard, that should serve the function of telling you that there's no robot code.
